// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To change project, use the "Switch Project" command in the menu.
export const firebaseConfig = {
  apiKey: 'AIzaSyBh56DqvEEKkE0Q6I-qTTFIoyuCsNUWlh8',
  authDomain: 'studio-6714657168-235bd.firebaseapp.com',
  projectId: 'studio-6714657168-235bd',
  storageBucket: 'studio-6714657168-235bd.appspot.com',
  messagingSenderId: '182363609451',
  appId: '1:182363609451:web:aaed74cc07261f6ad0142e',
};
